### ISSUE TITLE
Implement project documentation, documents and presentation

### ISSUE THREAD

**Issue by PatrikTorn** [joomp/groovy#12]

**Comment by samuelhelen** [comment]
pull request file

quality issues xlsx

diary xlsx

**Comment by PatrikTorn** [comment]
Okko - Sonarcloud issues excel + powerpoint dia
Joona - G14-diary excel + powerpoint dia
Samuel - Implementation of feature powerpoint dia
Patrik - general powerpoint dias

**Comment by samuelhelen** [comment]
Zenhub burn_down_chart.jpg
