### ISSUE TITLE
Investigate the location of the feature from the project code

### ISSUE THREAD

**Issue by PatrikTorn** [joomp/groovy#8]

**Comment by xaaria** [comment]
The `File.write(String s)` is defined in subproject _groovy-nio_ and methods live in `NioExtensions.java`

see https://github.com/apache/groovy/blob/59e14e1d6d4a21dbba2222963f9984dda9f15e18/subprojects/groovy-nio/src/main/java/org/apache/groovy/nio/extensions/NioExtensions.java
